In [40]:
import pandas as pd
import numpy as np

In [41]:
train_data_file ='SpamData/02_Training/train_data.txt'
test_data_file ='SpamData/02_Training/test_data.txt'
vocab_size = 2500

In [42]:
#Read and Load features from .txt files into numpy array
sparse_train_data = np.loadtxt(train_data_file,delimiter=' ',dtype=int)
sparse_test_data = np.loadtxt(test_data_file,delimiter=' ',dtype=int)

In [43]:
sparse_train_data[:5] #first 5 rows

array([[ 0,  2,  1,  1],
       [ 0,  3,  1,  2],
       [ 0,  4,  1,  1],
       [ 0,  7,  1,  3],
       [ 0, 11,  1,  1]])

In [44]:
sparse_train_data[-5:] #last 5 rows

array([[5798, 2035,    0,    2],
       [5798, 2040,    0,    1],
       [5798, 2272,    0,    1],
       [5798, 2342,    0,    1],
       [5798, 2370,    0,    1]])

In [45]:
print(sparse_train_data.shape[0],'==> No of rows in TRAIN file')
print(sparse_test_data.shape[0],'==> No of rows in TEST file')

263535 ==> No of rows in TRAIN file
112601 ==> No of rows in TEST file


In [46]:
print(np.unique(sparse_train_data[:,0]).size,'==> No of emails in TRAIN file')
print(np.unique(sparse_test_data[:,0]).size,'==> No of emails in TEST file')
#[:,0] ==> Notation for selecting all the rows in the 0th column.

4012 ==> No of emails in TRAIN file
1725 ==> No of emails in TEST file


# Creating a full Matrix

In [47]:
column_names=['DOC_ID']+['CATEGORY']+list(range(0,vocab_size))
column_names[:5]

['DOC_ID', 'CATEGORY', 0, 1, 2]

In [48]:
len(column_names)

2502

In [49]:
index_names = np.unique(sparse_train_data[:,0])
index_names

array([   0,    1,    2, ..., 5796, 5797, 5798])

In [50]:
full_train_data = pd.DataFrame(index=index_names,columns=column_names)
full_train_data.fillna(value=0,inplace=True)
#fillna fills the na values with 0s

In [51]:
full_train_data.head()

DOC_ID  CATEGORY  0  1  2  3  4  5  6  7  ...  2490  2491  2492  2493  \
0       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
1       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
2       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
3       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
4       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   

   2494  2495  2496  2497  2498  2499  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     0     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 2502 columns]

# Creating a Full Matrix from Sparse Matrix

In [60]:
def make_full_matrix(sparse_matrix,no_words,doc_idx=0,word_idx=1,cat_idx=2,freq_idx=3):
    #no_words - size of vocabulary
    #doc_idx=0 - position of document id in sparse matrix set to 1st column
    #word_idx=1 - position of word id in sparse matrix set to 2nd column 
    #cat_idx=2 - position of label/category (spam -> 1 , non-spam -> 0) set to 3rd column
    #freq_idx=3 - position of occurrence of word  id in sparse matrix set to 1st column
    column_names = column_names=['DOC_ID']+['CATEGORY']+list(range(0,vocab_size))
    doc_id_names = np.unique(sparse_matrix[:,0])
    full_matrix = pd.DataFrame(index=index_names,columns=column_names)
    full_matrix.fillna(value=0,inplace=True)
    for i in range(sparse_matrix.shape[0]):
        doc_no = sparse_matrix[i][doc_idx]
        word_id = sparse_matrix[i][word_idx]
        label = sparse_matrix[i][cat_idx]
        occurence = sparse_matrix[i][freq_idx]
        
        full_matrix.at[doc_no,'DOC_ID'] = doc_no
        full_matrix.at[doc_no,'CATEGORY'] = label
        full_matrix.at[doc_no,word_id] = occurence
    full_matrix.set_index('DOC_ID',inplace=True)
    return full_matrix

In [61]:
%%time
full_train_data = make_full_matrix(sparse_train_data,vocab_size)

CPU times: total: 32.8 s
Wall time: 33.3 s


In [62]:
full_train_data.head()

CATEGORY  0  1  2  3  4  5  6   7  8  ...  2490  2491  2492  2493  \
DOC_ID                                        ...                           
0              1  0  0  1  2  1  0  0   3  0  ...     0     0     0     0   
1              1  7  1  2  0  1  0  0   1  0  ...     0     0     0     0   
2              1  6  1  1  0  1  0  0   1  0  ...     0     0     0     0   
3              1  6  0  0  2  4  0  3  14  0  ...     0     0     0     0   
4              1  5  1  2  0  1  0  0   1  0  ...     0     0     0     0   

        2494  2495  2496  2497  2498  2499  
DOC_ID                                      
0          0     0     0     0     0     0  
1          0     0     0     0     0     0  
2          0     0     0     0     0     0  
3          0     0     0     0     0     0  
4          0     0     0     0     0     0  

[5 rows x 2501 columns]